version: '3.2'

services:
  # laravel stack
  web:
    env_file: 
      - .env
    container_name: laravel-elastic-docker-nginx-latest
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-elastic:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - mysql
      - redis
    networks: 
      - elk
  php:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel-elastic-docker-php-fpm
    image: devilbox/php-fpm:7.4-prod-0.106
    restart: always
    volumes:
      - ./laravel-elastic:/var/www
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
    depends_on:
      - mysql
    networks: 
      - elk
  mysql:
    env_file: 
      - .env
    container_name: laravel-elastic-docker-mysql
    image: mysql:5.6.26
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel-elastic
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - elk
  redis:
    env_file: 
      - .env
    container_name: laravel-elastic-docker-redis
    restart: always
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks: 
      - elk
  # elasticsearch
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.10.1
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
